config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # devise_for :admins
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_scope :admin do
    get '/admin', to: 'admins/sessions#new'
  end

  namespace :admins do
    resources :dashboards do
      get :index, on: :collection
    end
    resources :posts
    resources :podcasts

  end
  # mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  validates_uniqueness_of :title
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ApplicationController
    # before_action :authenticate_admin!
    # layout 'admin'
  end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::BaseController
  
    def index
     end
  end

app/controllers/admins/podcasts_controller.rb
 class Admins::PodcastsController < Admins::BaseController

   def index
     @podcasts = Podcast.all
     respond_to do |format|
       format.html
       format.json {
         render json: PodcastDatatable.new(view_context, { recordset: @podcasts })
       }
     end
   end

     def new
       @podcast = Podcast.new
     end

     def create
       @podcast = Podcast.new(podcast_params)

       if @podcast.save
         redirect_to podcasts_path, notice: 'Podcast was successfully created.'
       else
         render :new
       end
     end

     def edit
       @podcast = Podcast.find(params[:id])
     end

   def show
     @podcast = Podcast.find(params[:id])
   end

     def update
       if @podcast.update(podcast_params)
         redirect_to podcasts_path, notice: "Podcast was successfully updated."
       else
         render :edit
       end
     end

     def destroy
       @podcast.destroy
       redirect_to podcasts_path, notice: 'Podcast was successfully destroyed.'
     end

     private

     def set_podcast
       @podcast = Podcast.find_by(id: params[:id])
     end

     def podcast_params
       params.require(:podcast).permit(:image, :audio, :audio_url, :title, :description, :position, :is_active, :podcast_id)
     end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < Admins::BaseController
    before_action :get_post, only: [:show]
  
    def index
       @posts = Post.all
      respond_to do |format|
        format.html
        format.json {
          render json: PostDatatable.new(view_context, { recordset: @posts }) }
      end
    end
  
    def new
      @post = Post.new
    end
    def show
      @post = Post.find(params[:id])
    end
  
    private
  
    def get_post
      @post = Post.find_by(id: params[:id])
    end
  end
  

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
    layout false
    # before_action :configure_sign_in_params, only: [:create]
    def after_sign_in_path_for(resource)
      admins_dashboards_path
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/dashboards/index.html.erb
<h1> admin dashboard </h1>

app/views/admins/podcasts/_form.html.erb
<div class="profile_page">
  <div class="col-12 col-lg-8 col-md-12">
    <div class="card border-0 rounded-4 mb-4">
      <div class="card-body p-4">
        <!-- app/views/podcasts/_form.html.erb -->
        <%= form_with(model: @podcast, url: @podcast.persisted? ? admins_podcasts_path(@podcast) : admins_podcasts_path, method: @podcast.persisted? ? :patch : :post) do |f| %>
          <% if @podcast.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@podcast.errors.count, 'error') %> prohibited this podcast from being saved:</h2>

              <ul>
                <% @podcast.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>            <div class="card-header mb-4 p-0 bg-white border-0 d-flex justify-content-between w-100 align-items-center">
        <h2 class="m-0 fs-18">Podcast Information</h2>
        <div class="d-flex align-align-center gap-3">
          <button class="btn edit_btn bg-primary text-white px-3 py-2 rounded-5"><%= @podcast.new_record? ? 'Save' : 'Update' %> Changes</button>
          <%= link_to 'Back', admins_podcasts_path, class:'btn btn-outline-primary px-3 py-2 rounded-5' %>
        </div>
      </div>
          <div class="d-lg-flex d-block gap-2">
            <div class="w-100 mb-3">
              <div class="form-group">
                <%= f.label :title, class: "fs-14 fw-lighter text-secondary required" %>
                <%= f.text_field :title, class: "form-control p-3 fs-14 text-secondary bg-white", placeholder: "title", required: true %>
              </div>
            </div>
          </div>
          <div class="d-lg-flex d-block gap-2">
            <div class="w-100 mb-3">
              <div class="form-group mb-4">
                <%= f.label :podcast_url, class: "fs-14 fw-lighter text-secondary required" %>
                <%= f.text_field :podcast_id, class: "form-control p-3 fs-14 text-secondary bg-white", placeholder: "podcast id", required: true %>
              </div>
            </div>
          </div>
          <div class="col-lg-12">
            <div class="form-group mb-4">
              <div class="col-12">
                <div class="mb-3 file-single-upload">
                  <label class="fs-14 fw-lighter text-secondary">Podcast Picture</label>
                  <%= f.file_field :image, class: "filepond", accept: "image/*", 'data-controller': "media", 'data-media-target': "single", 'data-media-user-value': '{
                          }' %>
                </div>
              </div>
            </div>
          </div>
          <div class="d-lg-flex d-block gap-2">
            <div class="w-100 mb-3">
              <div class="form-group ">
                <%= f.label :Description, class: "fs-14 fw-lighter text-secondary required" %>
                <%= f.text_field :description, class: "form-control p-3 fs-14 text-secondary bg-white", placeholder: "Description", required: true %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/podcasts/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Dashboard', admins_dashboards_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Podcast', admins_podcasts_path %>
    </li>
    <li class="breadcrumb-item">
      Podcast bewerken
    </li>
  </ol>
</nav>
<h3>Podcast bewerken</h3>
<%= render "form" %>

app/views/admins/podcasts/index.html.erb
<h1>Podcasts Dashboard</h1>
<main id="dashboard" role="main" class="main">
  <div class="content container-fluid">
    <div class="mb-4" data-controller="datatable" data-source="<%= admins_podcasts_path(format: 'json') %>">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div class="input-group input-group-merge search-box" style="max-width: 450px">
          <div class="input-group-prepend input-group-text">
               <span class="input-group-text bg-transparent border-0 position-absolute" id="basic-addon1">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.5 21C16.7467 21 21 16.7467 21 11.5C21 6.25329 16.7467 2 11.5 2C6.25329 2 2 6.25329 2 11.5C2 16.7467 6.25329 21 11.5 21Z" stroke="#828282" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                    <path d="M22 22L20 20" stroke="#828282" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                  </svg>
              </span>
          </div>
          <input type="search" class="form-control search_list" placeholder="Search" data-action="keyup->datatable#customSearch">
        </div>
      </div>
      <div class="table-responsive-md datatable statistic-table" data-action="turbo:before-cache@document->datatable#destroyBeforeRender">
        <table class=" table align-middle table-nowrap" data-search="Enter For Search" aria-describedby="Podcast List">
          <thead>
            <tr>
              <th>Title</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/admins/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_podcasts_path, class: 'btn btn-secondary' %>

app/views/admins/podcasts/show.html.erb
show

<div class="training_details_page">
  <div class="row justify-content-end mb-4">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <%= link_to 'Dashboard', admins_dashboards_path %>
        </li>
        <li class="breadcrumb-item">
          <%= link_to 'Podcast', admins_podcasts_path %>
        </li>
        <li class="breadcrumb-item active"><%= @podcast.title %></li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="row mb-4 align-items-end">
        <div class="col-12 col-lg-3 col-md-9">
         </div>
        <div class="col-12 col-lg-9 col-md-7 py-3">
           <% if @podcast.podcast_id.present? %>
            <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/<%= @podcast.podcast_id %>?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
          <% else %>
            <p>No podcast available.</p>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="text-secondary fw-light">
          <h5 class="text-dark-blue fs-5 mb-4"> <%= @podcast.description %></h5>
          <%= @podcast.description%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/posts/index.html.erb
<h1>This is Posts Dashboard</h1>
<main id="dashboard" role="main" class="main">
  <div class="content container-fluid">
    <div class="mb-4" data-controller="datatable" data-source="<%= admins_posts_path(format: 'json') %>">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div class="input-group input-group-merge search-box" style="max-width: 450px">
          <div class="input-group-prepend input-group-text">
               <span class="input-group-text bg-transparent border-0 position-absolute" id="basic-addon1">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.5 21C16.7467 21 21 16.7467 21 11.5C21 6.25329 16.7467 2 11.5 2C6.25329 2 2 6.25329 2 11.5C2 16.7467 6.25329 21 11.5 21Z" stroke="#828282" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                    <path d="M22 22L20 20" stroke="#828282" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                  </svg>
              </span>
          </div>
          <input type="search" class="form-control search_list" placeholder="Search" data-action="keyup->datatable#customSearch">
        </div>
      </div>
      <div class="table-responsive-md datatable statistic-table" data-action="turbo:before-cache@document->datatable#destroyBeforeRender">
        <table class=" table align-middle table-nowrap" data-search="Enter For Search" aria-describedby="Post List">
          <thead>
          <tr>
            <th >ID</th>
            <th>Title</th>
            <th>Content</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPanel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>